name: Python test

on: [push]

jobs:
  lint_and_test :
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pipenv and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Lint with flake8
        run: |
          pipenv run flake8_only_critical
          pipenv run flake8_always_exit_zero

      - run: pipenv run mypy_strict

      - run: ./doctest.bash ./ds_scratch
